import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from "react-hot-toast"
import { NextAuthProvider } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cinematxt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster/>
      <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
